# Generated by Django 4.2.30 on 2026-06-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('malicious', 'Malicious')], max_length=20)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='network.subnet')),
            ],
        ),
    ]
