# Generated by Django 4.2.30 on 2026-06-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_address', models.CharField(max_length=255, unique=True)),
                ('cidr', models.IntegerField()),
                ('ip_version', models.IntegerField(choices=[(4, 'IPv4'), (6, 'IPv6')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('SAFE', 'Safe'), ('MALICIOUS', 'Malicious'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='network.subnet')),
            ],
            options={
                'verbose_name_plural': 'IP Analyses',
                'unique_together': {('subnet', 'ip_address')},
            },
        ),
    ]
